//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int studentID { get; set; }
        public string studentName { get; set; }
        public Nullable<int> standardID { get; set; }
        public string rowVersion { get; set; }
    
        public virtual address address { get; set; }
        public virtual Standard Standard { get; set; }
    }
}
